version: '3.9'
services:
  mysql-crudetudiant-db:
    image: mysql:8.0
    container_name: container_mysql-crudetudiant
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crudetudiantdb
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_HOST: '%'
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "user", "--password=user"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin-admin-db:
    container_name: container_phpmyadmin-crudetudiant
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8086:80"
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql-crudetudiant-db
      PMA_USER: user
      PMA_PASSWORD: user
    depends_on:
      - mysql-crudetudiant-db
    restart: unless-stopped

  springboot-crudetudiant-app:
    build: .
    container_name: springboot-crudetudiant-app
    ports:
      - "8089:8089"
    environment:
      DB_HOST: mysql-crudetudiant-db
      DB_NAME: crudetudiantdb
      DB_USERNAME: user
      DB_PASSWORD: user
    depends_on:
      - mysql-crudetudiant-db
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local
