server:
  port: 8089

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crudetudiantdb?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
  application:
    name: spring-crudetudiant
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    path: /api-docs

info:
  application:
    name: crud-etudiant
    version: '@project.version@'
