version: '3.8'
services:
  app:
    build: .
    ports:
      - "8089:8089"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/crudetudiantdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: Leviking
      SPRING_DATASOURCE_PASSWORD: Eldorado11
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: crudetudiantdb
      MYSQL_USER: Leviking
      MYSQL_PASSWORD: Eldorado11
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
