name: cicd github action

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-deploy:
    name: Build and Deploy app crud Etudiant
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
         java-version: 17
         distribution: 'corretto'
         cache: maven

      - name: Tests Unitaires
        run: mvn -B test --file pom.xml

      - name: Builder l'application
        run: | 
         mvn clean 
         mvn -B package --file pom.xml
